name: workflow-1
on: [ push, workflow_dispatch]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
      - name: Finish the job
        run: echo "Job 1 is finished"
  deploy:
    needs: job1 
    runs-on: ubuntu-latest
    steps: 
      - name: Get code # pulling the code from the repository
        uses: actions/checkout@v6
      - name: Install Node.js # installing node
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: Install dependencies # installing dependencies
        run: npm ciq
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."